fix: debug standalone and layer flavor

diff --git a/experiments/bash/runtime/bootstrap b/experiments/bash/runtime/bootstrap
--- a/experiments/bash/runtime/bootstrap
+++ b/experiments/bash/runtime/bootstrap
@@ -4,6 +4,18 @@ set -euo pipefail
 
 FILE="$LAMBDA_TASK_ROOT/$(echo "$_HANDLER" | cut -d. -f1).wasm"
 
+# Find wasmtime
+if [ -f "$LAMBDA_TASK_ROOT/wasmtime" ]; then
+  # Use wasmtime packaged with the function code
+  WASMTIME="$LAMBDA_TASK_ROOT"/wasmtime
+elif [ -f "/opt/bin/wasmtime" ]; then
+  # Use wasmtime provided through a Lambda layer
+  WASMTIME="/opt/bin/wasmtime"
+else
+  echo "wasmtime not found"
+  exit 1
+fi
+
 # Processing
 while true
 do
@@ -15,7 +27,7 @@ do
   REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)
 
   # Run the handler function from the script
-  RESPONSE=$("$LAMBDA_TASK_ROOT"/wasmtime -C cache=n "$FILE" "$EVENT_DATA")
+  RESPONSE=$($WASMTIME -C cache=n "$FILE" "$EVENT_DATA")
 
   # Send the response
   curl "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "$RESPONSE"
